<!-- Configurações -->
<input type="hidden" class="validate-config" id="valorASerPago" value="<?php echo $order->get_total(); ?>">
<input type="hidden" class="validate-config" name="content_type" value="<?php echo $configuracoes['content_type']; ?>">
<input type="hidden" class="validate-config" name="senha" value="<?php echo $configuracoes['senha']; ?>">
<input type="hidden" class="validate-config" name="nome" value="<?php echo $configuracoes['nome']; ?>">
<input type="hidden" class="validate-config" name="grupo" value="<?php echo $configuracoes['grupo']; ?>">
<input type="hidden" class="validate-config" name="cnpj" value="<?php echo $configuracoes['cnpj']; ?>">
<input type="hidden" class="validate-config" name="CNPJ_C02" value="<?php echo $configuracoes['CNPJ_C02']; ?>">
<input type="hidden" class="validate-config" name="nro_C07" value="<?php echo $configuracoes['nro_C07']; ?>">
<input type="hidden" class="validate-config" name="IE_C17" value="<?php echo $configuracoes['IE_C17']; ?>">
<input type="hidden" class="validate-config" name="cProd_I02" value="<?php echo $configuracoes['cProd_I02']; ?>">
<input type="hidden" class="validate-config" name="Formato" value="<?php echo $configuracoes['Formato']; ?>">
<input type="hidden" class="validate-config" name="numlote" value="<?php echo $configuracoes['numlote']; ?>">
<input type="hidden" class="validate-config" name="versao_A02" value="<?php echo $configuracoes['versao_A02']; ?>">
<input type="hidden" class="validate-config" name="tpImp_B21" value="<?php echo $configuracoes['tpImp_B21']; ?>">
<input type="hidden" class="validate-config" name="tpEmis_B22" value="<?php echo $configuracoes['tpEmis_B22']; ?>">
<input type="hidden" class="validate-config" name="cDV_B23" value="<?php echo $configuracoes['cDV_B23']; ?>">
<input type="hidden" class="validate-config" name="tpAmb_B24" value="<?php echo $configuracoes['tpAmb_B24']; ?>">
<input type="hidden" class="validate-config" name="INDFINAL_B25A" value="<?php echo $configuracoes['INDFINAL_B25A']; ?>">
<input type="hidden" class="validate-config" name="verProc_B27" value="<?php echo $configuracoes['verProc_B27']; ?>">
<input type="hidden" class="validate-config" name="uTrib_I13" value="<?php echo $configuracoes['uTrib_I13']; ?>">
<input type="hidden" class="validate-config" name="indTot_I17b" value="<?php echo $configuracoes['indTot_I17b']; ?>">
<input type="hidden" class="validate-config" name="CST_N12" value="<?php echo $configuracoes['CST_N12']; ?>">
<input type="hidden" class="validate-config" name="vFCPST_W06a" value="<?php echo $configuracoes['vFCPST_W06a']; ?>">
<input type="hidden" class="validate-config" name="vFCPSTRet_W06b" value="<?php echo $configuracoes['vFCPSTRet_W06b']; ?>">
<input type="hidden" class="validate-config" name="NCM_I05" value="<?php echo $configuracoes['NCM_I05']; ?>">
<input type="hidden" class="validate-config" name="CEST_I05c" value="<?php echo $configuracoes['CEST_I05c']; ?>">
<input type="hidden" class="validate-config" name="CNPJ_ZD02" value="<?php echo $configuracoes['CNPJ_ZD02']; ?>">
<input type="hidden" class="validate-config" name="xContato_ZD04" value="<?php echo $configuracoes['xContato_ZD04']; ?>">
<input type="hidden" class="validate-config" name="email_ZD05" value="<?php echo $configuracoes['email_ZD05']; ?>">
<input type="hidden" class="validate-config" name="fone_ZD06" value="<?php echo $configuracoes['fone_ZD06']; ?>">
<input type="hidden" class="validate-config" name="serie_B07" value="<?php echo $configuracoes['serie_B07']; ?>">
<input type="hidden" class="validate-config" name="nNF_B08" value="<?php echo $configuracoes['nNF_B08']; ?>">
<input type="hidden" class="validate-config" name="numero_do_pedido_woocommerce" value="<?php echo $id; ?>">
<input type="hidden" class="validate-config" name="pICMS_N16" value="<?php echo $configuracoes['base_calculo_icms']; ?>">
<!-- <input type="hidden" class="validate-config" name="vBCST_N21" value="<?php echo $configuracoes['base_calculo_icms_st']; ?>"> -->
<input type="hidden" class="validate-config" name="modBC_N13" value="<?php echo $configuracoes['mod_bc_icms']; ?>">